tasks:
 - init: >
     git clone https://github.com/algorithm-visualizer/server.git &&
     cd server &&
     echo -e "GITHUB_CLIENT_ID=dummy\nGITHUB_CLIENT_SECRET=dummy" > .env.local && npm install &&
     cd ..
   command: cd server && npm run watch
 - init: >
     npm install &&
     echo 'DANGEROUSLY_DISABLE_HOST_CHECK=true' > .env
   command: npm start
ports:
  - port: 3000
    onOpen: notify
  - port: 8080
    onOpen: ignore
